# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.CharField(default=1111111, max_length=32),
            preserve_default=False,
        ),
    ]
