# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default=111111, max_length=256),
            preserve_default=False,
        ),
    ]
